### ISSUE TITLE
System.EntryPointNotFoundException

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#128]
---------------------------
Microsoft Visual Studio
---------------------------
SQL Server Compact/SQLite Toolbox

System.EntryPointNotFoundException: Unable to find an entry point named 'sqlite3_open_interop' in DLL 'System.Data.SQLite.dll'.

at System.Data.SQLite.UnsafeNativeMethods.sqlite3_open_interop(Byte[] utf8Filename, Byte[] vfsName, SQLiteOpenFlagsEnum flags, Int32 extFuncs, IntPtr& db)

at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)

at System.Data.SQLite.SQLiteConnection.Open()

at ErikEJ.SQLiteScripting.SQLiteRepository..ctor(String connectionString)

at ErikEJ.SqlCeToolbox.Helpers.DataConnectionHelper.CreateRepository(DatabaseInfo databaseInfo)

at ErikEJ.SqlCeToolbox.ToolWindows.ExplorerControl.GetTableItems(Object sender, RoutedEventArgs args, KeyValuePair`2 database)

**Comment by ErikEJ** [comment]
Do you have SQLite installed in the GAC? Try to remove or install the latest version

**Comment by RicardoGarciaM** [comment]
Problem solved removing SQLite from GAC. Erik, many thanks for your quick help!

**Comment by ErikEJ** [comment]
Happy to help, let me know if you have any suggestions for improving this free tool!
