### ISSUE TITLE
Support SQLite tables with no data types

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#350]
When opening QtCreator's settings database (SQLite) no data may be inspected.

The table definition is as follows:
```
CREATE TABLE [settings] (
  [key]  NOT NULL
, [value]  NULL
, CONSTRAINT [sqlite_autoindex_settings_1] PRIMARY KEY ([key])
);
```

But a plain _SELECT_ yields:
```
System.ArgumentException: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.Couldn't store <System.Byte[]> in value Column.  Expected type is Int64. ---> System.InvalidCastException: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.
   at System.Data.Common.Int64Storage.Set(Int32 record, Object value)
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   --- End of inner exception stack trace ---
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   at System.Data.DataTable.NewRecordFromArray(Object[] value)
   at System.Data.DataTable.LoadRow(Object[] values, LoadOption loadOption, Index searchIndex)
   at System.Data.DataTable.LoadDataRow(Object[] values, LoadOption loadOption)
   at System.Data.ProviderBase.SchemaMapping.LoadDataRow()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.Common.LoadAdapter.FillFromReader(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.DataSet.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler, DataTable[] tables)
   at System.Data.DataSet.Load(IDataReader reader, LoadOption loadOption, String[] tables)
   at ErikEJ.SQLiteScripting.SQLiteRepository.RunCommand(String commandText, DataSet dataSet, Boolean ignoreDdlErrors)
   at ErikEJ.SQLiteScripting.SQLiteRepository.RunCommands(DataSet dataset, String script, Boolean checkSyntax, Boolean includePlan, Boolean ignoreDdlErrors)
   at ErikEJ.SQLiteScripting.SQLiteRepository.ExecuteSql(String script, Boolean& schemaChanged, Boolean ignoreDdlErrors)
   at ErikEJ.SqlCeToolbox.ToolWindows.SqlEditorControl.<>c__DisplayClass53_1.<ExecuteSqlScriptInEditor>b__0() in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\ToolWindows\SqlEditorControl.xaml.cs:line 556
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ErikEJ.SqlCeToolbox.ToolWindows.SqlEditorControl.<ExecuteSqlScriptInEditor>d__53.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\ToolWindows\SqlEditorControl.xaml.cs:line 554
```

No idea if SQLite offers a possibility to auto-detect the correct data type...but at least a hex-dump may be shown. What do you think, @ErikEJ?

### Further technical details
Toolbox version: ErikEJ.SqlCeScripting version 3.5.2.64

Database engine: SQLite

Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
I am using the system.data.sqlite ado.net provider. Have you tried with CAST ? http://www.sqlite.org/lang_expr.html#castexpr

**Comment by mwallnoefer** [comment]
Good catch, this works when you make use of custom _SELECT_ statements. But functions as **Edit Top 200 Rows** and **View Data as Report** do not...

No idea if there is some possibility to mitigate this.

**Comment by ErikEJ** [comment]
1: Please share a working query
2: Please show me a create table script created by the Toolbox

**Comment by mwallnoefer** [comment]
The _CREATE TABLE_ statement is shown above (I have copy & pasted it from SQL CE Toolbox).

This query does not work:
```
SELECT [key]
      ,[value]
  FROM [settings];
```
Such a query works (of course if both the key and value are in fact texts, which is not the general case):
```
SELECT cast([key] as text)
      ,cast([value] as text)
  FROM [settings];
```

**Comment by ErikEJ** [comment]
I am unable to come up with a general solution, closing and moving to backlog
