### ISSUE TITLE
Fails to View DBContext as Graph or Text if DBContext isn't using OnConfiguring to set connection string

### ISSUE THREAD

**Issue by snickler** [ErikEJ/SqlCeToolbox#491]
Describe what is not working as expected.

Clicking on View DBContext as a Graph or View DBContext as Text from a DBContext that isn't using OnConfiguring method to set the connection string gives the following errors:

1. If you have no parameterless constructor in your DBContext, you see this: 
![image](https://user-images.githubusercontent.com/4016293/30248622-2c2a41c2-95f9-11e7-8b9c-d4e89ad9e3e8.png)

2. If you throw a parameterless constructor into your DBContext to satisfy the previous error, you see this: 
> System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_Model()
>    at CallSite.Target(Closure , CallSite , Object )
>    at ReverseEngineer20.EFCoreModelAnalyzer.CreateDebugView(Object context)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at ReverseEngineer20.EFCoreModelAnalyzer.GenerateDebugView(Object context)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at EFCorePowerTools.Handlers.ModelAnalyzerHandler.GenerateDebugView(Object contextType) in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 23
> 

### Steps to reproduce

1. Create a Data project, create a sample DBContext with some data applied or scaffold an existing one
2. Configure the DbContext to support DI per https://docs.microsoft.com/en-us/ef/core/miscellaneous/configuring-dbcontext#constructor-argument
3. Reference the Data project from a ASPNetCore 2.0 project
4. Insert the DI code for AddDbContext in Startup.cs
5. Determine that the main NetCore 2.0 project can properly read data from the DbContext after building
6. Right click on the DbContext -> EF Core Power Tools and select either View DBContext as Graph or View DBContext as Text.

It seems to assume that the DBContextOptions are to be configued within the OnConfiguring override of the DBContext, rather than a Context Factory or pulling from the services container.

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)
Entity Framework Core Power Tools 0.1
Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2015, SSMS 16.5.3)
Visual Studio 2017 (15.3.2)

**Comment by ErikEJ** [comment]
Can you provide the sample project? TIA!

**Comment by ErikEJ** [comment]
Wonder if this is related: https://github.com/aspnet/Announcements/issues/258

**Comment by snickler** [comment]
Actually, I was able to reproduce this by running "dotnet new mvc --auth Individual" to create a new project that would generate a DBContext and trying the operations on the ApplicationDbContext.cs under the Data folder.

I also randomly start getting System.Runtime errors while doing any operations (Clicking on another .cs file, or trying to save) in VS after I get the "No parameterless constructor error"

![image](https://user-images.githubusercontent.com/4016293/30248929-c8906dca-95fe-11e7-9f1b-d2d8689d851c.png)

**Comment by ErikEJ** [comment]
OK, are you able to provide a zipped repro project?

**Comment by snickler** [comment]
[testapp.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1290492/testapp.zip)

**Comment by ErikEJ** [comment]
I think you are basically suffering from my limited capabilities:
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/EFCorePowerTools/EFCorePowerToolsPackage.cs#L193

**Comment by snickler** [comment]
I'm thinking that logic has to act similar to the EF Core Add Migration logic. It should create an application services container based upon the assembly. From there, it can load the IConfiguration object and grab the implementation of the services, then the DbContext should load properly

**Comment by ErikEJ** [comment]
Sure, but I am not there yet.

**Comment by snickler** [comment]
Hmmm, it looks like that might be the case. I'm glad to help any way I can, though. By testing and seeing if maybe I can find something to resolve :)

**Comment by ErikEJ** [comment]
I will see if there are any workarounds

**Comment by ErikEJ** [comment]
In the solution you sent me, I added a .NET Standard library, add EF Core SQL Server NuGet and created this class:

```csharp
using Microsoft.EntityFrameworkCore;

namespace DataAccess
{
    public class MyContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Db=Dummy");
            }
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public string MyProperty { get; set; }
    }
}

```

I was then able to create the model and view the graph

**Comment by snickler** [comment]
Yup. This requires OnConfiguring to work. Most people use the Dependency Injection pattern which doesn't work in this scenario. Although, I wonder if you can create a .NET Standard Library and pass an IConfiguration into the OnConfiguring part to retrieve the connection string? If that works, then that would be a pretty preferred way of doing this.

**Comment by ErikEJ** [comment]
You can pass an DbOptionsBuilder

**Comment by snickler** [comment]
Yeah. I was speaking about still reading from the JSON configuration in order to pass in the that connection string to configure the DbOptionsBuilder. I'm going to try something and post whether it works or not

**Comment by snickler** [comment]
Actually, what I wanted to try won't work. It would have to instantiate the IConfiguration before anything (it's always null when running the tool). I'd rather not completely hard code a connection string.

**Comment by ErikEJ** [comment]
You should be able to pass the config value to a class in your data access lib, and the construct a DbOPtionsBuilder

**Comment by snickler** [comment]
I should be able to do that, but it wouldn't work via the View DBContext as ____. 

Also, I tried something with the testapp. I added the OnConfiguring override and put in 

 optionsBuilder.UseSqlite("DataSource=app.db");

When I run it, I can consistently receive the following error, even when restarting VS numerous times.  

![image](https://user-images.githubusercontent.com/4016293/30251624-6e37e398-9631-11e7-95e4-f0b14f4649c0.png)

**Comment by snickler** [comment]
Oh.. I wonder if it's a problem with my Visual Studio. I realized on here I'm running 15.3.1 instead of 15.3.2. I'm going to update to the latest 2017 update and see if my errors go away.

**Comment by snickler** [comment]
Nope. I updated to 15.3.3 and I'm still getting:

> Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.


Is there anything in this extension that's explicitly looking for System.Diagnostics.DiagnosticSource? Immediately after I get this error, I start getting the System.Runtime errors and have to restart Visual Studio. I'm going to try explicitly adding the latest System.Diagnostics.DiagnosticSource Nuget package and see if that helps

**Comment by ErikEJ** [comment]
Any update - tried latest build ?

**Comment by snickler** [comment]
I'll try the latest in an hour and let you know :).

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ErikEJ** [comment]
I have published an alternative approach here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools#view-dbcontext-model-as-graph

**Comment by snickler** [comment]
This is what I received by trying the latest vsix as of 5 minutes ago

![image](https://user-images.githubusercontent.com/4016293/30319543-289c87b4-977e-11e7-8799-2a6760cd7dd8.png)

**Comment by snickler** [comment]
Using the snippet for the DGMLBuilder and running with IISExpress, I get the following error 

System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at testapp.Controllers.HomeController.Index() in C:\testapp\Controllers\HomeController.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by ErikEJ** [comment]
That last error does not look like it is related to anything here !?

**Comment by ErikEJ** [comment]
Oh, sorry, you cannot launch Visual Studio for a web app! Just save the file, and later open in VS!

**Comment by ErikEJ** [comment]
Just a FYI, I was finally able to repro your issue, and has changed the DGFML feature to just add the NuGet package in the current project

**Comment by ErikEJ** [comment]
I have now added a feature to add DbContext Model diagram(s) to the current project, currently only works for .NET Framework projects.

**Comment by snickler** [comment]
Awesome!

Thanks :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
