### ISSUE TITLE
EFCore Power Tools could not connect to Azure SQL database

### ISSUE THREAD

**Issue by luedi** [ErikEJ/SqlCeToolbox#516]
To evaluate the EFCore power tools i created a .NET Core 2.0 class library project. When i try to connect to an Azure SQL database (which is an Sql Server 2014 under the hood) the connection attempt fails with the following exception:
```
System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'dba'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at ErikEJ.SqlCeScripting.ServerDBRepository..ctor(String connectionString, Boolean keepSchemaName)
   at ErikEJ.SqlCeToolbox.Helpers.RepositoryHelper.CreateRepository(DatabaseInfo databaseInfo) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\RepositoryHelper.cs:line 17
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__3.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 110
ClientConnectionId:e773cdd0-52d5-489a-8fd7-f782b142ddf8
Error Number:18456,State:1,Class:14
```
I'm using SQL Server authentification. Connecting via Sql Server Management Studio is successful. Calling Scaffold-DbContext manually on the package manager console is also successful. Even if i test the connection in the connection dialog of the wizard the connection was successful.'

**Comment by ErikEJ** [comment]
Thanks for reporting this, fixed in the latest build (also on Marketplace) - build 377
