### ISSUE TITLE
EF Core Powertools: does not corretly recognize my .netstandard 2.0 library TargetframeworkMoniker

### ISSUE THREAD

**Issue by tnsturm** [ErikEJ/SqlCeToolbox#526]
Hello Eric,

as you requested, here comes my bug report:

Visual Studio 17 Version 15.4.1
EF Core Power Tools Extension Version 0.1.387
Nuget: ErikEJ.EntityFrameworkCore.DgmlBuilder, Version 1.0.3

I have packaged all my EF Core Models, Repositories and DBContext into a .NET Standard 2.0 libary.

When I do right click on the libaray project and select e.g. EF Core Power Tools => Add DBContext Model Diagram, EF Core PowerTools display error Dialog with:
"Currently only .NET Framework and .NET Core 2.0 projects are supported - TargetFrameworkMoniker: .NETStandard,Version=2.0"

my .csproj comes here:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>Database Objects</AssemblyTitle>
    <VersionPrefix>2.0</VersionPrefix>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DatabaseObjects</AssemblyName>
    <PackageId>DatabaseObjects</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="ErikEJ.EntityFrameworkCore.DgmlBuilder" Version="1.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="NRules" Version="0.7.2" />
    <PackageReference Include="Sendgrid" Version="9.9.0" />
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

</Project>
```

Best Regards,
Torsten

**Comment by ErikEJ** [comment]
Acutal project file:

```
<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
<AssemblyTitle>Database Objects</AssemblyTitle>
<VersionPrefix>2.0</VersionPrefix>
<TargetFramework>netstandard2.0</TargetFramework>
<AssemblyName>DatabaseObjects</AssemblyName>
<PackageId>DatabaseObjects</PackageId>
<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
<LangVersion>latest</LangVersion>
</PropertyGroup>

<ItemGroup>
<PackageReference Include="AutoMapper" Version="6.1.1" />
<PackageReference Include="ErikEJ.EntityFrameworkCore.DgmlBuilder" Version="1.0.3" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
<PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
<PackageReference Include="NRules" Version="0.7.2" />
<PackageReference Include="Sendgrid" Version="9.9.0" />
<PackageReference Include="System.ValueTuple" Version="4.4.0" />
</ItemGroup>

<ItemGroup>
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
</ItemGroup>

</Project>

```

**Comment by ErikEJ** [comment]
The error message is correct, pure .NET Standard 2.0 projects are NOT supported, as they generate no build output. 

You can work around the issue 
1: By targeting .NET Core also:

`<TargetFrameworks>netcoreapp2.0;netstandard2.0</TargetFrameworks>
`
(Notice the added "s"!) - TargetFramework**s**

2: By installing and using the AsDgml() extension method from for example a Unit test.

(and thanks for the review update, much appreciated)

I will add this info to the wiki page!

**Comment by ErikEJ** [comment]
Please let me know if the workarounds work for you!

**Comment by tnsturm** [comment]
workaround #2 workes

workaround #1: did you mean this as a work around on its own? when I replace TargetFramework with TargetFrameworks, following error is created:
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Das System kann die angegebene Datei nicht finden.
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Newtonsoft.Json'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)
   at System.Attribute.InternalGetCustomAttributes(PropertyInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.NotMappedMemberAttributeConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnEntityTypeAdded(OnEntityTypeAddedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at EyeQFlowDatabaseObjects.EyeQFlowDBContext..ctor(DbContextOptions`1 options) in C:\Users\torst\Source\Repos\FlowControl2017\src\EyeQFlowDatabaseObjects\DBContext\EyeQFlowDBContext.cs:line 36
   at EyeQFlowDatabaseObjects.EyeQFlowDBContextFactory.CreateDbContext(String[] optionStrings) in C:\Users\torst\Source\Repos\FlowControl2017\src\EyeQFlowDatabaseObjects\DBContext\EyeQFlowDBContext.cs:line 20
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at ReverseEngineer20.EfCoreModelBuilder.GenerateDatabaseCreateScript(String outputPath) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\ModelBuilder\EFCoreModelBuilder.cs:line 44
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\SqlCeToolbox\src\GUI\efpt\Program.cs:line 19



   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, Boolean generateDdl) in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 58

**Comment by ErikEJ** [comment]
Works for me - try to remove and re-add that package, perhaps?
