### ISSUE TITLE
EF Core Code First Approach Support

### ISSUE THREAD

**Issue by hafeefshaik** [ErikEJ/SqlCeToolbox#586]
Does this tool work with **_EF Code First_** Approach ?

Getting below mentioned error:

System.ArgumentException: Error:
System.ArgumentException: No EF Core DbContext types found in the project
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(String outputPath, DbContextOperations operations) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\ModelBuilder\EFCoreModelBuilder.cs:line 78
   at ReverseEngineer20.EfCoreModelBuilder.GenerateDebugView(String outputPath) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\ModelBuilder\EFCoreModelBuilder.cs:line 22
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\SqlCeToolbox\src\GUI\efpt\Program.cs:line 25

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 52
[DataPackagerRandD.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1538515/DataPackagerRandD.zip)

**Comment by ErikEJ** [comment]
Try to set the project with the DbContext as Startup project

**Comment by ErikEJ** [comment]
Yes, it works with any "approach" - but I see you are using EF 2.0.1: could you try the latest daily build, and let me know the result: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

**Comment by hafeefshaik** [comment]
It's working with daily build. Thanks for your quick response. Can I close the issues?
