### ISSUE TITLE
DbContext Only or EntityTypes Only does not work properly; generates both context and entities in any case

### ISSUE THREAD

**Issue by mbharodia** [ErikEJ/SqlCeToolbox#610]
Hello 

I tried using this tool and ran into a few issues. I though to share the details and wondering whether I can get any help to resolve them. Thank you

Visual Studio 2017
Version: 15.5.2 
Database: Sql sever 2016 developer edition
OS: Windows 10 Professional
Project type: .NET Standard 2.0 Class Library

I wanted to generate only Db Context; therefore I chose "DbContext Only". The tool still generated entity files. If I choose "Entity Types" only, the tool still generates Db Context file. I was hoping that the tool should generate both kinds only when I choose the relevant option. 

In addition to this, once files generated, I found the following in the output window. My table selection does not contain any table selection related to dbo.sysdiagrams or dbo._RefactorLog. I am not sure why the tool is trying to include them.

-----
Unable to find a table in the database matching the selected table dbo.sysdiagrams.
Unable to find a table in the database matching the selected table dbo.sysdiagrams.
Unable to find a table in the database matching the selected table dbo.sysdiagrams.
Unable to find a table in the database matching the selected table dbo.sysdiagrams.
Unable to find a table in the database matching the selected table dbo.sysdiagrams.
Index column dbo.__RefactorLog belongs to index PK____Refact__D3AEFFDB2525E882 on table OperationKey which is not included in the selection set. Skipping.
For index PK__sysdiagrams__7D78A4E7. Unable to find parent table dbo.sysdiagrams. Skipping index.
For index UK_principal_name. Unable to find parent table dbo.sysdiagrams. Skipping index.
For index UK_principal_name. Unable to find parent table dbo.sysdiagrams. Skipping index._
------

Moreover, when I ran the tool first time (including an option for HandleBar) in a class library where a folder named CodeTemplates was not available, I received the following error in the output window. At the first run the tool was able to add a new folder CodeTemplates but there were no POCO files or context generated. I tried running the tool again and it worked.

-----
System.InvalidOperationException: Destination directory 'C:\Projects\Test\Git\CCData\CCData\CodeTemplates' already exists.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<>c__DisplayClass5_0.<<AddFromDirectory>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.<>c__DisplayClass68_0`1.<<Mutate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass550_0.<<Mutate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Mutate(Func`1 asyncAction, Boolean includesFileSystemChange, String telemetryActivity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.Mutate[T](Func`1 asyncAction, Boolean includesFileSystemChange, String telemetryActivity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddFromDirectory(String directory)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 118
-----

**Comment by ErikEJ** [comment]
Thanks for the useful feedback, it would be very helpful if you could create 3 issue instead of 1, since you are reporting 3 distinct issue.

Re 1: I will investigate a fix for this.

Re 2: Those are just warnings, and can be ignored

re 3: Which version of the Power Tools are you running, I thought I had fixed this?

**Comment by mbharodia** [comment]
Sure, I will create separate threads. By the way, I have installed the tool from VS market place before a few hours: version is 1.0.491.

**Comment by ErikEJ** [comment]
Thanks, I just noticed that your project is .NET Standard, I think I have only fixed this for .NET Core projects.

**Comment by ErikEJ** [comment]
The CodeTemplates issue should be fixed in the latest daily build now

**Comment by ErikEJ** [comment]
Just leave this open for your original issue, there is nothing I can do about the warnings.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, let me know if it works for you, and thanks for reporting these issues.

**Comment by mbharodia** [comment]
The latest build worked for me! Thank you so much for your help.

**Comment by mbharodia** [comment]
Do you want me to create different threads for these issues? Please let me know.

**Comment by ErikEJ** [comment]
No, if both the bugs you reported have been fixed, you do not need to do anything
