### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by mvaneijk** [ErikEJ/SqlCeToolbox#614]
I got the following error:
```
System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c.<FindContextTypes>b__12_5(TypeInfo t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 72
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 32
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\SqlCeToolbox\src\GUI\efpt\Program.cs:line 26



Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 52
```
### Steps to reproduce
When trying:
Right Click Project -> EF Core Power Tool -> Add DbContext Model Diagram

### Further technical details
My project only includes the `Microsoft.EntityFrameworkCore.Tools` v2.0.1

Toolbox/Power Tools version: 4.7.491.0

Database engine: SQL Server

Visual Studio: Community 2017 15.5.3

**Comment by ErikEJ** [comment]
Can you share your project (or at least csproj file) ?

**Comment by mvaneijk** [comment]
Here you go (I replaced some names with ***)
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>aspnet-***-EDF7BD55-7989-4F97-B8F4-C3522F384E15</UserSecretsId>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\require-config.ts" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Akka" Version="1.3.2" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" PrivateAssets="All" />
    <PackageReference Include="QRCoder" Version="1.3.2" />
    <PackageReference Include="***.Portable" Version="2.2.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="Scripts\dashboard.ts" />
    <TypeScriptCompile Include="Scripts\require-config.ts" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\site.css" />
    <None Include="wwwroot\js\***.js" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
    <TypeScriptModuleKind>AMD</TypeScriptModuleKind>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>True</TypeScriptNoImplicitAny>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptOutFile />
    <TypeScriptOutDir />
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptMapRoot>C:\***</TypeScriptMapRoot>
    <TypeScriptSourceRoot>C:\***</TypeScriptSourceRoot>
  </PropertyGroup>

</Project>
```

**Comment by ErikEJ** [comment]
Could you provide a simple project that demonstrates the issue?

**Comment by ErikEJ** [comment]
Closing as repro project not received

**Comment by hafeefshaik** [comment]
@ErikEJ even I am facing the same issues. To reproduce the issue, create a empty .net core project. and add a datacontext which is inherit form IdentityDbContext<T>, then run the migrations, then try to generate the dbcontext diagram.

**Comment by ErikEJ** [comment]
@hafeefshaik Could you share a .zip file with a repro project?

**Comment by hafeefshaik** [comment]
[ManifestIdentityWebApp.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1699259/ManifestIdentityWebApp.zip)

**Comment by hafeefshaik** [comment]
Please delete the attachment once you download the code. Thanks

**Comment by ErikEJ** [comment]
Thanks - and deleted

**Comment by ErikEJ** [comment]
I was able to repro, but not able to find a fix...

**Comment by CraigRaelHarris** [comment]
I get similar when trying to "reverse" a postgres db:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlServerCe, Version=3.5.1.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

**Comment by hafeefshaik** [comment]
@ErikEJ actually I am form web background. is there a document how to setup dev environment for this project ?

**Comment by ErikEJ** [comment]
@CraigRaelHarris Postgres is not supported by the tool right now, but you should have gotten a clearer error message - please create a new issue with the full stack trace, thanks (it is completely unrelated to this issue)

**Comment by ErikEJ** [comment]
@hafeefshaik What "project" are you referring to?

**Comment by ErikEJ** [comment]
@CraigRaelHarris I have improved the error message in the latest daily build

**Comment by hafeefshaik** [comment]
@ErikEJ I am using sql server in attached project.

**Comment by hafeefshaik** [comment]
@ErikEJ  As suggested created new ticket.

please create a new issue with the full stack trace, thanks (it is completely unrelated to this issue)

**Comment by ErikEJ** [comment]
@hafeefshaik Thanks, but it was in relation to @CraigRaelHarris  posting

**Comment by ErikEJ** [comment]
Closing this and leaving the new issue open!
