### ISSUE TITLE
Add dbContext model diagram not wroking when dbcontext inherits from IdentityDbContext<T>

### ISSUE THREAD

**Issue by hafeefshaik** [ErikEJ/SqlCeToolbox#628]
Getting below error:

System.ArgumentException: Error:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> System.IO.FileNotFoundException: Could not load the specified file.
File name: 'Microsoft.AspNetCore.Identity.EntityFrameworkCore'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c.<FindContextTypes>b__12_5(TypeInfo t)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.FindContextTypes()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.GetContextTypes()
   at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 72
   at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\SqlCeToolbox\src\GUI\ReverseEngineer20\EFCoreModelBuilder.cs:line 32
   at ReverseEngineer20.Program.Main(String[] args) in C:\Code\SqlCeToolbox\src\GUI\efpt\Program.cs:line 26

Parameter name: processResult
   at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 52

Add DbContext Model Diagram is not working as expect.

### Steps to reproduce
To reproduce the issue, create a empty .net core project. and add a datacontext which is inherit form IdentityDbContext, then run the migrations, then try to generate the dbcontext diagram.

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
Does the workaround of adding the AsDgml extension method work? (as describd in the wiki article)

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Could potentailly be fixed by improving how dotnet is called: C:\Code\EntityFramework\src\dotnet-ef\RootCommand.cs

**Comment by hafeefshaik** [comment]
@ErikEJ sorry for delay, let me give a try by adding AsDgml()  extension method.

**Comment by ErikEJ** [comment]
Thanks, I will have a look!

**Comment by ErikEJ** [comment]
@DrewBrasher  thanks for reporting this - fixed in version 1.0.9 - I would be very grateful if you could provide a DebugView text file, so I can add a test for this!

**Comment by DrewBrasher** [comment]
@ErikEJ I sent you the DebugText file.  I also realized that my original project had some more places with the invalid character that the example I sent you didn't have so I sent a new dgml file as well.
The other lines are like these:
`<Node Id = "ApplicationUser.Claims" Label="Claims (*)" Name="Claims" Category="Navigation Collection" Type="ICollection&lt;IdentityUserClaim&lt;string&gt;&gt;"  Field="&lt;Claims&gt;k__BackingField" Dependent="IdentityUserClaim<string>" Principal="" Inverse="" PropertyAccessMode="PropertyAccessMode.Default" />`
and
`<Link Source="IdentityRoleClaim<string>" Target="IdentityRole" From="IdentityRoleClaim<string>.RoleId" To="IdentityRole.Id" Name="IdentityRoleClaim<string> -> IdentityRole" Annotations="" IsUnique="False" Label="1:*" Category="Foreign Key" />`

**Comment by ErikEJ** [comment]
Thanks!

Did you test the latest version of the NuGet package?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ErikEJ** [comment]
I see know that there are still issues! Working on it…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by DrewBrasher** [comment]
Updated to version 1.0.10.  Works great now thank you!

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#15
