### ISSUE TITLE
Handlebars option causes CodeTemplates directory exception

### ISSUE THREAD

**Issue by statler** [ErikEJ/SqlCeToolbox#682]
When opting to use the handlebars template, I get the following exception. This happens the very first time the handlebars option is selected, even if I ensure there is no CodeTemplates directory existing beforehand.

My project is based on .Net.47, although it does also have a .NET 2.0 Standard config that is not active.

`System.InvalidOperationException: Destination directory 'C:\Users\dennisg\Documents\Visual Studio 2017\Projects\cpDataCore\cpDataCore\CodeTemplates' already exists.
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<>c__DisplayClass5_0.<<AddFromDirectory>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.<>c__DisplayClass68_0`1.<<Mutate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass556_0.<<Mutate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Mutate(Func`1 asyncAction, Boolean includesFileSystemChange, String telemetryActivity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.Mutate[T](Func`1 asyncAction, Boolean includesFileSystemChange, String telemetryActivity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddFromDirectory(String directory)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 150`

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version 1.0

Database engine:SQL Server

Visual Studio or SSMS version:  Visual Studio 2017 15.6.4

**Comment by ErikEJ** [comment]
Can you share a repro project?

**Comment by statler** [comment]
Wish I could Erik, but unfortunately it is a private project. I created a fresh project on the same datasource and did not experience the issue.

I suspect it is something to do with the fact that the original project is multitargeted, so the logic tests preceding line 150 dont work as expected.

**Comment by ErikEJ** [comment]
Sounds like an issue with VS an multitargeted projects
