### ISSUE TITLE
No EF Core DbContext types found in the project

### ISSUE THREAD

**Issue by psijkof** [ErikEJ/SqlCeToolbox#687]
Whatever I try, adding references to the csproj file, or changing the target frameworks, using different databases, I am not able to generate (and view) the entity model. (The feature I look forward using the most!)

### Steps to reproduce
Add a .net core 2.0 console app.
Using (localdb)\mssqllocaldb any database I try.
Reverse engineer.
Try to add dbcontext model diagram, via right click on console app project.

### Further technical details
4.7.557.0

Database engine: 
SQL Server

Visual Studio Visual Studio 2017 15.6.5

**Comment by ErikEJ** [comment]
What Power Tools version do you have installed (there is an About menu item on the Power Tools context menu) - the version number you wrote (4.7.557) is for SQLite Toolbox.

**Comment by ErikEJ** [comment]
Fixed in latest daily build, and verified working with .NETCoreapp 2.0 with EF Core 2.0.0, 2.0.1 and 2.0.2 - https://github.com/ErikEJ/SqlCeToolbox/wiki

**Comment by psijkof** [comment]
Thank you for the quick reply and actions. I'm a bit confused what extension I should download. The link point to the sqlce toolbox ... I'm currently working with ef core and sql server.

**Comment by psijkof** [comment]
With the following version, I have no luck:
Version 4.7.539.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No

System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Downloaded only ef core power tools, but I guess the. Sql ce toolbox was already installed....

Should I go for the latest build?

**Comment by ErikEJ** [comment]
You need VS Community or higher to view a DGML file

**Comment by psijkof** [comment]
I'm running VS CE 2017 latest. I see xml, no graphical representation.... Do i need another plugin?

**Comment by ErikEJ** [comment]
Yo have installed too few components! https://developercommunity.visualstudio.com/content/problem/24379/vs-2017-professional-can-no-longer-open-dgml-files.html

**Comment by ErikEJ** [comment]
Thanks for the review, pls let me know if you have any other feedback (ideas, bugs etc.)

**Comment by The-DevOps-Guy** [comment]
This issue seems to also occur with latest version EF core 2.2.0 and 2.2.1.
When selecting "Add DB context model diagram"

![image](https://user-images.githubusercontent.com/25591010/50968805-218cab00-14d4-11e9-9617-36cd8b5c5e10.png)

The error is;

> ========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
> 
> System.ArgumentException: Error:
> System.ArgumentException: No EF Core DbContext types found in the project
>    at ReverseEngineer20.EfCoreModelBuilder.GetDbContextTypes(DbContextOperations operations) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 76
>    at ReverseEngineer20.EfCoreModelBuilder.BuildResult(String outputPath, Boolean generateDdl) in C:\Code\EFCorePowerTools\src\GUI\efpt\EFCoreModelBuilder.cs:line 34
>    at ReverseEngineer20.Program.Main(String[] args) in C:\Code\EFCorePowerTools\src\GUI\efpt\Program.cs:line 44
> 
> Parameter name: processResult
>    at EFCorePowerTools.Handlers.ModelAnalyzerHandler.Generate(String outputPath, Project project, GenerationType generationType) in C:\projects\efcorepowertools\src\GUI\EFCorePowerTools\Handlers\ModelAnalyzerHandler.cs:line 49

nuget config

![image](https://user-images.githubusercontent.com/25591010/50968876-703a4500-14d4-11e9-8553-7f8d0f31cd6f.png)

**Comment by ErikEJ** [comment]
@The-DevOps-Guy  not sure it is related - Please share a repro.
