### ISSUE TITLE
When adding rows to a database, you can't edit them until reloading the query window

### ISSUE THREAD

**Issue by Mertsch** [ErikEJ/SqlCeToolbox#726]
When adding rows to a database, you can't edit them until reloading the query window

### Steps to reproduce
1. Create a new DB
2. Create a new Table with a text column
3. Insert Text into the column and repeat till you have 2 rows
4. Edit the text of the first item, get an error
5. Right click the table > Edit top 200 rows
6. Edit the text of the first item, now it works

```
---------------------------
Microsoft SQL Server Management Studio
---------------------------
SQLite / SQL Server Compact Toolbox

System.Data.DBConcurrencyException: Concurrency violation: the UpdateCommand affected 0 of the expected 1 records.

   at System.Data.Common.DbDataAdapter.UpdatedRowStatusErrors(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)

   at System.Data.Common.DbDataAdapter.UpdatedRowStatus(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)

   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)

   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows)

   at ErikEJ.SqlCeToolbox.WinForms.ResultsetGrid.UpdateRowToDatabase() in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\WinForms\ResultsetGrid.cs:line 294
---------------------------
OK   
---------------------------
```

### Further technical details
Toolbox for SSMS 4.7.460
Database engine: SQlite
SSMS version: 17.8.1

**Comment by ErikEJ** [comment]
Does your new table have a primary key?

**Comment by Mertsch** [comment]
I am not an SQLite expert, so if a new table does not, then no

**Comment by ErikEJ** [comment]
This will only work for table with primary keys, and may not always work anyway - due to flaws in data binding outside of my control. You can always modify data via UPDATE statements instead.
