### ISSUE TITLE
Timeout when scripting SQL Server DB to SQLite

### ISSUE THREAD

**Issue by PeterVD-Lansweeper** [ErikEJ/SqlCeToolbox#803]
Hi,

The toolbox (SSMS version) fails to create a SQLite script based on a sql server database (>600 tables, >14000 columns). I get a timeout error.
Is it possible to increase the timeout value?

This is the error I get.

_System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at System.Data.SqlClient.SqlDataReader.get_MetaData()

   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)

   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)

   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)

   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)

   at System.Data.SqlClient.SqlCommand.ExecuteReader()

   at ErikEJ.SqlCeScripting.ServerDBRepository.ExecuteReader[T](String commandText, AddToListDelegate`1 addToListMethod)

   at ErikEJ.SqlCeScripting.ServerDBRepository.GetAllColumns()

   at ErikEJ.SqlCeScripting.Generator.Init(IRepository repository, String outFile)

   at ErikEJ.SqlCeScripting.Generator..ctor(IRepository repository, String outFile, Boolean azure, Boolean preserveSqlDates, Boolean sqlite)

   at ErikEJ.SqlCeToolbox.Helpers.DataConnectionHelper.CreateGenerator(IRepository repository, String outFile, DatabaseType databaseType) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\DataConnectionHelper.cs:line 583

   at ErikEJ.SqlCeToolbox.Commands.SqlServerDatabaseMenuCommandsHandler.ScriptServerDatabase(Object sender, ExecutedRoutedEventArgs e) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Commands\SqlServerDatabaseMenuCommandsHandler.cs:line 78

ClientConnectionId:6396ecd8-4abc-4e17-92b0-327e10e7b921

Error Number:-2,State:0,Class:11_

**Comment by Random96** [comment]
Hi After install and was connected to .sdf file, studio was random crashed Visual studio 2019 community edition 16.3.2 russian localisation trace:Приложение: devenv.exeВерсия платформы: v4.0.30319Описание. Процесс был завершен из-за необработанного исключения.Сведения об исключении: System.ComponentModel.InvalidAsynchronousStateExceptionв System.Windows.Forms.Control.WaitForWaitHandle(System.Threading.WaitHandle)в System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)в System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])в Microsoft.VSDesigner.ServerExplorer.ServerExplorerThread.RunThread()в System.Threading.ThreadHelper.ThreadStart_Context(System.Object)в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)в System.Threading.ThreadHelper.ThreadStart() Bad application name: devenv.exe, version: 16.3.29326.143, timestamp: 0x5d8d7ebaFailed module name: KERNELBASE.dll, version: 10.0.18362.10022, timestamp: 0x8c4198abException Code: 0xe0434352Error Offset: 0x00113522Failed Process ID: 0x421cApplication start-up time: 0x01d57a66af2c090eBad Application Path: C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Community \ Common7 \ IDE \ devenv.exeFailed module path: C: \ WINDOWS \ System32 \ KERNELBASE.dllReport ID: f968122b-1156-4d03-a4fc-1cfaf11b12fbFull name of the failed package:Bad application related code:   04.10.2019, 13:09, "Peter Van Dender" <notifications@github.com>:Describe what is not working as expected.Steps to reproduceInclude a complete description that I can redo to reproduce the issue.Further technical detailsToolbox/Power Tools version: (found in About dialog - blue questionmark icon)Database engine: (SQlite, SQL Compact or SQL Server)Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ErikEJ** [comment]
@Random96 Please create a new issue, thanks!

**Comment by ErikEJ** [comment]
@PeterVD-Lansweeper I think this is fixed in the latest VS version - https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes#release-47644-may-21-2019 - can you try that?

**Comment by PeterVD-Lansweeper** [comment]
Indeed it is. My SSMS toolbox version wasn't updated yet. The VS2017 toolbox was and works fine.
Thanks. :-)
