### ISSUE TITLE
cannot remove the SQL EXPRESS connection that does not exist any more

### ISSUE THREAD

**Issue by BKAppsPlus** [ErikEJ/SqlCeToolbox#807]
I have Visual Studio : (e.g. Visual Studio 2017 15.9.13
I added the local instance of my SQL SERVER EXPRESS (machinename/SQLEXPRESS)
1-I cannot drill down to the tables, etc. ,
2-When I right-click on the connection there is no option to remove the connection.
3- if I turn off the SQLEXPRESS Service on my local machine and then right-clicking on the "Data Connections" and clicking on the "Remove broken connections" results in : and the connection still stays there in the Data Connections

---------------------------
Microsoft Visual Studio
---------------------------
SQLite/SQL Server Compact Toolbox

System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)

   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)

   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)

   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)

   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)

   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)

   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)

   at System.Data.SqlClient.SqlConnection.Open()

   at ErikEJ.SqlCeScripting.ServerDBRepository..ctor(String connectionString, Boolean keepSchemaName)

   at ErikEJ.SqlCeToolbox.Helpers.RepositoryHelper.CreateRepository(DatabaseInfo databaseInfo) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\RepositoryHelper.cs:line 20

   at ErikEJ.SqlCeToolbox.Helpers.DataConnectionHelper.ValidateConnections(SqlCeToolboxPackage package) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\DataConnectionHelper.cs:line 335

   at ErikEJ.SqlCeToolbox.Commands.DatabasesMenuCommandsHandler.FixConnections(Object sender, ExecutedRoutedEventArgs e) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Commands\DatabasesMenuCommandsHandler.cs:line 234

ClientConnectionId:00000000-0000-0000-0000-000000000000

Error Number:-1,State:0,Class:20
---------------------------
OK   
---------------------------

**Comment by ErikEJ** [comment]
You can open Server Explorer to remove the connection.
