### ISSUE TITLE
COMException in GetSqlCeFilesInProjectItems if WiX project is included in solution

### ISSUE THREAD

**Issue by dirvo** [ErikEJ/SqlCeToolbox#842]
We have several solutions that include Windows Installer XML projects (based on the Votive extension https://wixtoolset.org/documentation/manual/v3/votive/). 

If the button _Add SQLite and SQL Compact connections from the current Solution_ in the toolbox windows is clicked, the following exception is raised and shown in a popup dialog:

```
---------------------------
Microsoft Visual Studio
---------------------------
SQLite/SQL Server Compact Toolbox

System.Runtime.InteropServices.COMException (0x80020003): Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Package.Automation.OAProjectItem`1.get_Kind()
   at ErikEJ.SqlCeToolbox.Helpers.EnvDteHelper.GetSqlCeFilesInProjectItems(ProjectItems projectItems, HashSet`1 list) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\EnvDTEHelper.cs:line 155
   at ErikEJ.SqlCeToolbox.Helpers.EnvDteHelper.GetSqlCeFilesInProjectItems(ProjectItems projectItems, HashSet`1 list) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\EnvDTEHelper.cs:line 173
   at ErikEJ.SqlCeToolbox.Helpers.EnvDteHelper.GetSqlCeFilesInProjectItems(ProjectItems projectItems, HashSet`1 list) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\EnvDTEHelper.cs:line 169
   at ErikEJ.SqlCeToolbox.Helpers.EnvDteHelper.GetSqlCeFilesInActiveSolution(DTE dte) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\EnvDTEHelper.cs:line 129
   at ErikEJ.SqlCeToolbox.Helpers.DataConnectionHelper.ScanConnections(SqlCeToolboxPackage package) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Helpers\DataConnectionHelper.cs:line 345
   at ErikEJ.SqlCeToolbox.Commands.DatabasesMenuCommandsHandler.ScanConnections(Object sender, ExecutedRoutedEventArgs e) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Commands\DatabasesMenuCommandsHandler.cs:line 219
---------------------------
OK   
---------------------------
```

Apparently, the `ProjectItem.Kind` property isn't valid/available for all project types and the extension should only check those projects where this property is available. As this is a `COMException` and there is no other way to check the validity of the property before accessing it, there is probably no way around explicitly catching this exception whenever the `ProjectItem.Kind` property is accessed.

### Steps to reproduce

1. Install WiX and the Votive extensions
2. Create a new solution, add a C# project and a WiX/Votive project to the solution
3. Open the _SQLite/SQL Server Compact Toolbox_ window and press the button _Add SQLite and SQL Compact connections from the current Solution_

### Possible Workaround

It seems to help to unload the unsupported project(s) from the solution.

### Further technical details
Toolbox/Power Tools version: 

```
Version 4.7.670.0 - 1.575.172 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8482.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes
```

Database engine: SQlite

Visual Studio version: VS 2019 16.5.4

**Comment by ErikEJ** [comment]
Ignored for 5 years - https://github.com/wixtoolset/issues/issues/4200  - I will look into ignoring the error - and happily accept a PR!

**Comment by ErikEJ** [comment]
I attempted a fix in the latest daily build, please let me know if that works for you.
