### ISSUE TITLE
Tool stop working

### ISSUE THREAD

**Issue by rouf0007** [ErikEJ/SqlCeToolbox#964]
Describe what is not working as expected.

I got this message:

System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.SafeNativeMethods.MessageBox(HandleRef hWnd, String text, String caption, Int32 type)
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   at ErikEJ.SqlCeToolbox.WinForms.ResultsetGrid.ResultsetGrid_Load(Object sender, EventArgs e) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\WinForms\ResultsetGrid.cs:line 82

... and Visual Studio 2022:

Microsoft Visual Studio Community 2022
Version 17.6.4
VisualStudio.17.Release/17.6.4+33815.320
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

SQL Server Data Tools   17.6.13.0
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

Query first 200 row on table 

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
Fixed in latest daily build https://www.vsixgallery.com/extension/41521019-e4c7-480c-8ea8-fc4a2c6f50aa

**Comment by rouf0007** [comment]
Thank you very much.

**Comment by rouf0007** [comment]
I have a new problem after installing the Syncfusion component.

I'm working with an old project (2010) and a 3.5 framework that I need to
support during the migration to Net 7.

Now I get this message:

[image: image.png]
I read the KB article 974247 but it refers to the "SQL Server Compact 3.5"
version rather than the 4.0 version.To get around the problem I installed
SSMS and the "SSMS 17 Extension" component but it fails to install (log
file in the attachment). Now I don't know what I should do. Do you have a
suggestion or something to read?

Thanks

François


Le jeu. 6 juill. 2023, à 09 h 29, Francois Rouleau ***@***.***> a
écrit :

> Thank you very much.
>
> Le jeu. 6 juill. 2023, à 04 h 53, Erik Ejlskov Jensen <

**Comment by rouf0007** [comment]
Hello
I found the problem: SqlServerCe version 3.5 was installed (via
SyncFusion?) at the same time as version 4. I uninstalled 3.5 and
everything is back to normal.

Sorry for the inconvenience

François

Le dim. 30 juill. 2023, à 16 h 40, Francois Rouleau ***@***.***> a
écrit :

> I have a new problem after installing the Syncfusion component.
>
> I'm working with an old project (2010) and a 3.5 framework that I need to
> support during the migration to Net 7.
>
> Now I get this message:
>
> [image: image.png]
> I read the KB article 974247 but it refers to the "SQL Server Compact 3.5"
> version rather than the 4.0 version.To get around the problem I installed
> SSMS and the "SSMS 17 Extension" component but it fails to install (log
> file in the attachment). Now I don't know what I should do. Do you have a
> suggestion or something to read?
>
> Thanks
>
> François
>
>
> Le jeu. 6 juill. 2023, à 09 h 29, Francois Rouleau ***@***.***> a
> écrit :
>
>> Thank you very much.
>>
>> Le jeu. 6 juill. 2023, à 04 h 53, Erik Ejlskov Jensen <
