### ISSUE TITLE
Entry point not found

### ISSUE THREAD

**Issue by fohatpete2** [ErikEJ/SqlCeToolbox#989]
Attempts to open / test a connection show the following messagebox in VS2022 (latest):

---------------------------
Microsoft Visual Studio
---------------------------
System.EntryPointNotFoundException: Unable to find an entry point named 'SI17c3a78ecf9eff4c' in DLL 'SQLite.Interop.dll'.

   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_open_interop(Byte[] utf8Filename, Byte[] vfsName, SQLiteOpenFlagsEnum flags, Int32 extFuncs, IntPtr& db)

   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)

   at System.Data.SQLite.SQLiteConnection.Open()

   at ErikEJ.SqlCeToolbox.Dialogs.SQLiteConnectionDialog.TestConnection(Boolean showMessage) in C:\projects\sqlcetoolbox\src\GUI\SqlCe35Toolbox\Dialogs\SQLiteConnectionDialog.xaml.cs:line 57

---------------------------
OK   
---------------------------

**Comment by ErikEJ** [comment]
Is System.Data.Sqlite installed in GAC, and if so, which version?

**Comment by fohatpete2** [comment]
No. Should the extension have installed it?
________________________________

**Comment by ErikEJ** [comment]
No, but the errors message could indicate a mismatch in versions from the extension vs the version in GAC

**Comment by ErikEJ** [comment]
Ping?

**Comment by fohatpete2** [comment]
Working now. Did something change, or was it just me 🙂?
________________________________

**Comment by ErikEJ** [comment]
I did not change anything...
